Correct bugs in high resolution hdpara creation scripting

diff --git a/run/templates/components.tmpl b/run/templates/components.tmpl
--- a/run/templates/components.tmpl
+++ b/run/templates/components.tmpl
@@ -43,6 +43,12 @@ working_directory=${repository_path}/projects/${project_name}/workdir
 
 {% macro create_project_dirs(is_create_project_script=false) %}
 #Prepare folders
+{% if not is_create_project_script %}
+if [[ -e ${repository_path}/projects/${project_name} ]]; then
+  echo "Error - project directory already exists" 1>&2
+  exit 1
+fi
+{%- endif -%}
 mkdir -p ${repository_path}/projects
 mkdir -p ${repository_path}/projects/${project_name}
 mkdir -p ${input_directory}
@@ -56,7 +62,6 @@ cd ${working_directory}
 
 {% macro set_variables_post_user_input() %}
 icon_atmo_grid_res=$(echo ${icon_atmo_grid_res} | tr [:upper] [:lower] | tr -d 0)
-icon_ocean_grid_res=$(echo ${icon_ocean_grid_res} | tr [:upper] [:lower] | tr -d 0)
 etop01_filepath=/work/mj0060/m300468/data/ETOPO1_Ice_g_gmt4_grid_registered.nc
 config_filepath=${working_directory}/bash_script.cfg
 python_config_filepath=${working_directory}/python_script.cfg
@@ -151,9 +156,14 @@ if ${use_true_sinks}; then
 else
   true_sinks_flag_string=""
 fi
-output_hdpara_filepath=${output_directory}/hdpara_${icon_atmo_grid_res}_${icon_atmo_grid_id}_sc_${binary_conversion_method}_${true_sinks_flag_string}v${version_num}.nc
-output_catchments_filepath=${output_directory}/catch_${icon_atmo_grid_res}_${icon_atmo_grid_id}_sc_${binary_conversion_method}_${true_sinks_flag_string}v${version_num}.nc
-output_accumulated_flow_filepath=${output_directory}/acc_${icon_atmo_grid_res}_${icon_atmo_grid_id}_sc_${binary_conversion_method}_${true_sinks_flag_string}v${version_num}.nc
+{% if input.high_res %}
+number_of_channels_label_string="_mc_"
+{% else %}
+number_of_channels_label_string="_sc_"
+{% endif %}
+output_hdpara_filepath=${output_directory}/hdpara_${icon_atmo_grid_res}_${icon_atmo_grid_id}_${icon_ocean_grid_id}_${number_of_channels_label_string}_${binary_conversion_method}_${true_sinks_flag_string}v${version_num}.nc
+output_catchments_filepath=${output_directory}/catch_${icon_atmo_grid_res}_${icon_atmo_grid_id}_${icon_ocean_grid_id}_${number_of_channels_label_string}_${binary_conversion_method}_${true_sinks_flag_string}v${version_num}.nc
+output_accumulated_flow_filepath=${output_directory}/acc_${icon_atmo_grid_res}_${icon_atmo_grid_id}_${icon_ocean_grid_id}_${number_of_channels_label_string}_${binary_conversion_method}_${true_sinks_flag_string}v${version_num}.nc
 {%- endmacro -%}
 
 {% macro preprocessing() %}
@@ -190,7 +200,7 @@ if ! ${use_existing_river_mouth_position_file} ; then
   river_mouth_position_filepath=
 fi
 #Run bifurcated hdpara file generation
-cmd="${repository_path}/Dynamic_HD_bash_scripts/generate_icon_hdpara_top_level_driver.sh ${orography_filepath} ${binary_lsmask_filepath} ${true_sinks_filepath} "z" "landsea" "true_sinks" ${output_hdpara_filepath} ${ $output_catchments_filepath} ${output_accumulated_flow_filepath}  ${config_filepath} ${working_directory} ${icon_grid_filepath} False True ${river_mouth_position_filepath}
+cmd="${repository_path}/Dynamic_HD_bash_scripts/generate_icon_hdpara_top_level_driver.sh ${orography_filepath} ${binary_lsmask_filepath} ${true_sinks_filepath} "z" "landsea" "true_sinks" ${output_hdpara_filepath} ${ $output_catchments_filepath} ${output_accumulated_flow_filepath}  ${config_filepath} ${working_directory} ${icon_grid_filepath} ${icon_atmo_grid_res} False True ${river_mouth_position_filepath}
 {% else %}
 cmd="${repository_path}/Dynamic_HD_bash_scripts/generate_icon_hdpara_top_level_driver.sh ${orography_filepath} ${binary_lsmask_filepath} ${output_hdpara_filepath} ${output_catchments_filepath} ${output_accumulated_flow_filepath} ${config_filepath} ${working_directory} ${icon_grid_filepath} ${repository_path}/Dynamic_HD_Resources/cotat_plus_standard_params.nl ${icon_atmo_grid_res} False ${use_hfrac} ${maxl_binary_lsmask_filepath} ${true_sinks_filepath}"
 {% endif %}
