Almost complete prototype for template generator at low resolution

diff --git a/run/templates/components.tmpl b/run/templates/components.tmpl
--- a/run/templates/components.tmpl
+++ b/run/templates/components.tmpl
@@ -1,20 +1,89 @@
+{%- macro header() -%}
+!/bin/bash
+{% if input.slurm_headers -%}
+#SLURM HEADERS
+#SBATCH --job-name=create_icon_hdpara
+#SBATCH --partition=shared
+#SBATCH --account=YOURACCOUNT
+#SBATCH --ntasks=1
+#SBATCH --time=02:00:00
+#SBATCH --output=create_icon_hdpara.o%j    # File name for standard output
+#SBATCH --error=create_icon_hdpara.e%j     # File name for standard error output
+#SBATCH --mail-type=FAIL                   # Notify user by email in case of job failure
+#SBATCH --mail-user=YOUR EMAIL
+{%- endif -%}
+
+{% endmacro -%}
+
+{% macro set_variables_pre_user_input() %}
+script_path=$(dirname ${0})
+project_name=$(basename ${0})
+{%- if input.create_project_at_runtime -%}
+repository_path=${script_path%/run}
+{%- else -%}
+repository_path=${script_path%/projects/*/scripts}
+{%- endif -%}
+input_directory=${repository_path}/projects/${project_name}/input
+output_directory=${repository_path}/projects/${project_name}/output
+working_directory=${repository_path}/projects/${project_name}/workdir
+{%- endmacro -%}
+
+{% macro set_variables_post_user_input() %}
+etop01_filepath=/work/mj0060/m300468/data/ETOPO1_Ice_g_gmt4_grid_registered.nc
+config_filepath=
+binary_lsmask_filepath=${working_directory}/binary_lsmask.nc
+orography_filepath=${working_directory}/orography.nc
+{%- endmacro -%}
+
+{% macro create_project_dirs() %}
+#Prepare folders
+
+mkdir -p ${repository_path}/projects
+mkdir -p ${repository_path}/projects/${project_name}
+mkdir -p ${input_directory}
+mkdir -p ${output_directory}
+mkdir -p ${working_directory}
+{%- if input.script_type == 'createproject' -%}
+mkdir -p ${repository_path}/projects/${project_name}/scripts/
+{%- endif -%}
+{%- endmacro -%}
+
 {% macro preproc() %}
 # Pre-processing
-{% endmacro %}
+if [[ ${binary_conversion_method} == "hfrac" ]]; then
+  cdo expr,cell_sea_land_mask='(cell_sea_land_mask > 0.5)' ${fractional_lsmask_filepath} ${binary_lsmask_filepath}
+  cdo expr,cell_sea_land_mask='(cell_sea_land_mask > 0.0)' ${fractional_lsmask_filepath} ${max_land_binary_lsmask_filepath}
+elif [[ ${binary_conversion_method} == "minl" ]]; then
+  cdo expr,cell_sea_land_mask='(cell_sea_land_mask >= 1.0)' ${fractional_lsmask_filepath} ${binary_lsmask_filepath}
+  cdo expr,cell_sea_land_mask='(cell_sea_land_mask >  0.0)' ${fractional_lsmask_filepath} ${max_land_binary_lsmask_filepath}
+elif [[ ${binary_conversion_method} == "maxl" ]]; then
+  cdo expr,cell_sea_land_mask='(cell_sea_land_mask >  0.0)' ${fractional_lsmask_filepath} ${binary_lsmask_filepath}
+else
+  exit 1
+fi
+
+cdo remapbil,${icon_grid_filepath} ${etop01_filepath} ${orography_filepath}
+{%- endmacro -%}
 
 {% macro postproc() %}
 # Post Processing
-{% endmacro %}
+# (No post-processing required at present)
+{%- endmacro -%}
 
 {% macro clean() %}
 # Clean-up
-{% endmacro %}
+echo "Post run clean-up not yet implemented!"
+{%- endmacro -%}
 
 {% macro report_pre() %}
 # Prepare preliminary report
-{% endmacro %}
+echo "Preliminary report not yet implemented!"
+#python ${repository_path}/utils/run_utilities/prepare_report.py prelim
+{%- endmacro -%}
 
 {% macro report_post() %}
 # Prepare post-run report
-{% endmacro %}
+echo "Post run report not yet implemented!"
+#python ${repository_path}/utils/run_utilities/prepare_report.py post
+{%- endmacro -%}
 
